# [ GENERAL ]
max_gwei: 100                     # Максимальный гвей, которого будет ждать софт.
use_proxy: false                  # Использовать прокси
# [ DELAYS ]
need_delay_acc: true              # Нужна задержка между акками? true/false Да/Нет
delay_acc_min: 10                 # Мин. задержка - целые числа.
delay_acc_max: 15                 # Макс. задержка - целые числа.


# [ TELEGRAM ]
telegram_alerts: false             # Использовать телеграм уведомления? true/false Да/Нет
bot_token: ""                     # Токен телеграм бота. Получить в @botfather. После того как создадите бота, напишите ему /start.
chat_id: 680906123                # Ваш id телеграм. Получать в @myidbot командой -> "/getid"

# [ OKX SETTINGS]
need_okx: false                   # Выводить средства с OKX

okx_value_min: 0.002              # Мин. значение эфира вывода с OKX
okx_value_max: 0.003              # Макс. значение эфира вывода с OKX
oxk_apiKey: ""                    # 
oxk_secret: ""                    #
oxk_password: ""                  #